
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SentimentAnalysis_ConsoleApp_v1
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.OutputEncoding = System.Text.Encoding.UTF8;
			SentimentAnalysisModel model = new SentimentAnalysisModel();
			do
			{
				Console.Write("\nEnter your comment: ");
				string userinput = Console.ReadLine();
				// Create single instance of sample data from first line of dataset for model input
				SentimentAnalysisModel.ModelInput sampleData = new SentimentAnalysisModel.ModelInput()
				{
					Comment = userinput,
				};
				Console.WriteLine("Please wait...");
				// Make a single prediction on the sample data and print results
				var predictionResult = model.Predict(sampleData);

				Console.WriteLine($"Predicted Rating_star: {predictionResult.Prediction}");

				Console.Write("Press any key to continue, press Esc to exit");
				var keyInfo = Console.ReadKey();
				if (keyInfo.Key == ConsoleKey.Escape)
					break;
			} while (true);

		}
	}
}
